app:
  bot-api-base: http://localhost:8080
  github:
    api-base: https://api.github.com
    token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    api-base: https://api.stackexchange.com/2.3
    key: ${SO_TOKEN_KEY}
  scheduling:
    cron: "0 * * * * ?"
    offset-minutes: 1

logging:
  structured:
    format:
      file: ecs
  file:
    name: scrapper-log.json

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
