app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  scrapper-api-base: http://localhost:8081

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  structured:
    format:
      file: ecs
  file:
    name: bot-log.json

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
